title: 臺灣自由開源 L10N 社群支援站
url: https://l10n.tw
logo: /images/android-chrome-192x192.png
image: /images/l10n-tw_thumbnail.webp
social:
    name: L10n Taiwan
    links:
        - https://github.com/l10n-tw/
locale: zh_TW

exclude: [README.md]
navigation:
    - title: 最新快訊
      url: "/"
    - title: 文化
      url: "/culture/"
    - title: 翻譯
      url: "/translate/"
    - title: 字型
      url: "/font/"
    - title: 開發
      url: "/development/"
    - title: 社群
      url: "/community/"
    - title: 標誌
      url: "https://l10n.tw/l10n-tw-logo/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      AMP: true
      INFO: false
      INFO-ICON: info
plugins:
    - jekyll-seo-tag